#research_task:
#  description: >
#    Conduct a thorough research about {topic}
#    Make sure you find any interesting and relevant information given
#    the current year is {current_year}.
#  expected_output: >
#    A list with 10 bullet points of the most relevant information about {topic}
#  agent: researcher

#reporting_task:
#  description: >
#    Review the context you got and expand each topic into a full section for a report.
#    Make sure the report is detailed and contains any and all relevant information.
#  expected_output: >
#    A fully fledged report with the main topics, each with a full section of information.
#    Formatted as markdown without '```'
#  agent: reporting_analyst

task_research_recipe:
  description: >
    Research popular and highly-rated recipes specifically about {recipe_theme}.
    Use the search tool to find promising recipe ideas.
    Select ONE specific recipe that seems suitable for a blog post.
    Extract its name, a brief description, the main ingredients (list format),
    and a summary of the key preparation steps.
  expected_output: >
    A concise summary report containing:
    1. The chosen Recipe Name.
    2. A brief Description of the recipe.
    3. A list of the Main Ingredients.
    4. A short Summary of the key preparation steps.
  agent: recipe_researcher

task_seo_analysis:
  description: >
    Perform an SEO analysis for the recipe identified in the previous step.
    Use the search tool for this analysis. Specifically:
    1. Identify 3-5 primary and secondary SEO keywords relevant to the recipe name and topic.
    2. Find 1-2 top-ranking online articles for this specific recipe.
    3. Briefly analyze the structure (headings, main sections) and key angles 
    (e.g., quick/easy, specific occasion, dietary focus) of these competitor articles.
  expected_output: >
    A report containing:
    1. A list of 3-5 recommended SEO keywords (primary and secondary).
    2. A brief summary of the structure and key angles observed in 1-2 top competitor articles.
  agent: seo_specialist

  