task_research_recipe:
  description: >
    Research popular and highly-rated recipes at this moment.
    Use the search tool to find promising recipe ideas.
    Select ONE specific recipe that seems suitable for a blog post.
    Extract its name, a brief description, the main ingredients (list format),
    and a summary of the key preparation steps.
  expected_output: >
    A concise summary report containing:
    1. The chosen Recipe Name.
    2. A brief Description of the recipe.
    3. A list of the Main Ingredients.
    4. A short Summary of the key preparation steps.
  agent: recipe_researcher

task_seo_analysis:
  description: >
    Perform an SEO analysis for the recipe identified in the previous step.
    Use the search tool for this analysis. Specifically:
    1. Identify 3-5 primary and secondary SEO keywords relevant to the recipe name and topic.
    2. Find 1-2 top-ranking online articles for this specific recipe.
    3. Briefly analyze the structure (headings, main sections) and key angles 
    (e.g., quick/easy, specific occasion, dietary focus) of these competitor articles.
  expected_output: >
    A report containing:
    1. A list of 3-5 recommended SEO keywords (primary and secondary).
    2. A brief summary of the structure and key angles observed in 1-2 top competitor articles.
  agent: seo_specialist
  context: 
    - task_research_recipe

task_write_recipe:
  description: >
    Using the selected recipe from the previous step, write a detailed and engaging recipe blog post.
    The blog post should include:
      - A catchy title
      - An introductory paragraph that hooks the reader
      - A formatted list of ingredients
      - Step-by-step instructions
      - Optional tips or serving suggestions
  expected_output: >
    A blog article formatted in Markdown, ready to be edited or published.
  agent: recipe_writer
  context:
    - task_seo_analysis 

task_human_editing:
  description: >
    Edit the previously written recipe blog post to improve its tone and flow.
    Make the writing feel more human and natural, like a warm and friendly food blogger.
    Keep the structure but rewrite awkward or robotic parts. Add a bit of personality.
  expected_output: >
    A polished version of the blog article with a more human, friendly, and natural tone.
    Keep the formatting (title, intro, ingredients, steps), but improve transitions, 
    add warmth, and remove stiff language.
  agent: human_editor
  context:
    - task_write_recipe